In [2]:
import numpy as np

def tiled_matrix_multiplication(A, B, tile_size):
    m, n = A.shape
    n, p = B.shape
    C = np.zeros((m, p))

    for i in range(0, m, tile_size):
        for j in range(0, p, tile_size):
            for k in range(0, n, tile_size):
                # Extract tiles from A and B
                A_tile = A[i:i+tile_size, k:k+tile_size]
                B_tile = B[k:k+tile_size, j:j+tile_size]
                
                # Perform matrix multiplication on tiles
                C_tile = np.dot(A_tile, B_tile)
                
                # Update the result matrix C
                C[i:i+tile_size, j:j+tile_size] += C_tile
                
                print(f"Step: i={i}, j={j}, k={k}")
                print("A_tile:")
                print(A_tile)
                print("B_tile:")
                print(B_tile)
                print("C_tile:")
                print(C_tile)
                print("Current C:")
                print(C)
                print()

    return C

In [3]:

# Example usage
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

tile_size = 2

result = tiled_matrix_multiplication(A, B, tile_size)
print("Final result:")
print(result)

Step: i=0, j=0, k=0
A_tile:
[[1 2]
 [5 6]]
B_tile:
[[1 2]
 [4 5]]
C_tile:
[[ 9 12]
 [29 40]]
Current C:
[[ 9. 12.  0.]
 [29. 40.  0.]
 [ 0.  0.  0.]]

Step: i=0, j=0, k=2
A_tile:
[[3 4]
 [7 8]]
B_tile:
[[ 7  8]
 [10 11]]
C_tile:
[[ 61  68]
 [129 144]]
Current C:
[[ 70.  80.   0.]
 [158. 184.   0.]
 [  0.   0.   0.]]

Step: i=0, j=2, k=0
A_tile:
[[1 2]
 [5 6]]
B_tile:
[[3]
 [6]]
C_tile:
[[15]
 [51]]
Current C:
[[ 70.  80.  15.]
 [158. 184.  51.]
 [  0.   0.   0.]]

Step: i=0, j=2, k=2
A_tile:
[[3 4]
 [7 8]]
B_tile:
[[ 9]
 [12]]
C_tile:
[[ 75]
 [159]]
Current C:
[[ 70.  80.  90.]
 [158. 184. 210.]
 [  0.   0.   0.]]

Step: i=2, j=0, k=0
A_tile:
[[ 9 10]]
B_tile:
[[1 2]
 [4 5]]
C_tile:
[[49 68]]
Current C:
[[ 70.  80.  90.]
 [158. 184. 210.]
 [ 49.  68.   0.]]

Step: i=2, j=0, k=2
A_tile:
[[11 12]]
B_tile:
[[ 7  8]
 [10 11]]
C_tile:
[[197 220]]
Current C:
[[ 70.  80.  90.]
 [158. 184. 210.]
 [246. 288.   0.]]

Step: i=2, j=2, k=0
A_tile:
[[ 9 10]]
B_tile:
[[3]
 [6]]
C_tile:
[[87]]
Current

In [6]:
list(range(0, 16, 4))

[0, 4, 8, 12]

In [8]:
A@B

array([[ 70,  80,  90],
       [158, 184, 210],
       [246, 288, 330]])

In [9]:
import math

In [10]:
1/math.sqrt(2048)

0.022097086912079608